// This file will be generated by Supabase CLI
// Run: npx supabase gen types typescript --project-id <project-id> > lib/supabase/types.ts

export type Database = {
  public: {
    Tables: {
      campaigns: {
        Row: {
          id: string
          name: string
          campaign_type: 'political_election' | 'political_issue' | 'brand_awareness' | 'product_launch' | 'promo' | 'ngo_issue'
          start_date: string
          end_date: string
          primary_goal_type: 'awareness' | 'engagement' | 'list_building' | 'conversion' | 'mobilization'
          secondary_goals: unknown
          description: string | null
          budget_estimate: number | null
          status: 'planning' | 'running' | 'closed'
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['campaigns']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Omit<Database['public']['Tables']['campaigns']['Row'], 'id' | 'created_at' | 'updated_at'>>
      }
      goals: {
        Row: {
          id: string
          campaign_id: string
          title: string
          description: string | null
          target_metric: unknown | null
          priority: number
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['goals']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Omit<Database['public']['Tables']['goals']['Row'], 'id' | 'created_at' | 'updated_at'>>
      }
      segments: {
        Row: {
          id: string
          campaign_id: string
          name: string
          description: string | null
          demographics: unknown | null
          psychographics: unknown | null
          priority: number | null
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['segments']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Omit<Database['public']['Tables']['segments']['Row'], 'id' | 'created_at' | 'updated_at'>>
      }
      topics: {
        Row: {
          id: string
          campaign_id: string
          name: string
          description: string | null
          category: string | null
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['topics']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Omit<Database['public']['Tables']['topics']['Row'], 'id' | 'created_at' | 'updated_at'>>
      }
      messages: {
        Row: {
          id: string
          campaign_id: string
          segment_id: string | null
          topic_id: string | null
          message_type: 'core' | 'supporting' | 'contrast'
          headline: string
          body: string | null
          proof_point: string | null
          cta: string | null
          status: 'draft' | 'approved'
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['messages']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Omit<Database['public']['Tables']['messages']['Row'], 'id' | 'created_at' | 'updated_at'>>
      }
      channels: {
        Row: {
          id: string
          name: string
          type: 'social' | 'paid' | 'owned'
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['channels']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Omit<Database['public']['Tables']['channels']['Row'], 'id' | 'created_at' | 'updated_at'>>
      }
      campaign_channels: {
        Row: {
          campaign_id: string
          channel_id: string
          weight: number | null
        }
        Insert: Database['public']['Tables']['campaign_channels']['Row']
        Update: Partial<Database['public']['Tables']['campaign_channels']['Row']>
      }
      sprints: {
        Row: {
          id: string
          campaign_id: string
          name: string
          start_date: string
          end_date: string
          focus_goal: string | null
          focus_channels: unknown
          status: 'planned' | 'active' | 'closed'
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['sprints']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Omit<Database['public']['Tables']['sprints']['Row'], 'id' | 'created_at' | 'updated_at'>>
      }
      tasks: {
        Row: {
          id: string
          campaign_id: string
          sprint_id: string | null
          channel_id: string | null
          title: string
          description: string | null
          category: 'creative' | 'copy' | 'social_setup' | 'ads_setup' | 'analytics' | 'coordination' | null
          status: 'todo' | 'in_progress' | 'done'
          assignee: string | null
          due_date: string | null
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['tasks']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Omit<Database['public']['Tables']['tasks']['Row'], 'id' | 'created_at' | 'updated_at'>>
      }
    }
    Views: {}
    Functions: {}
    Enums: {
      campaign_type: 'political_election' | 'political_issue' | 'brand_awareness' | 'product_launch' | 'promo' | 'ngo_issue'
      goal_type: 'awareness' | 'engagement' | 'list_building' | 'conversion' | 'mobilization'
      campaign_status: 'planning' | 'running' | 'closed'
      message_type: 'core' | 'supporting' | 'contrast'
      message_status: 'draft' | 'approved'
      sprint_status: 'planned' | 'active' | 'closed'
      task_category: 'creative' | 'copy' | 'social_setup' | 'ads_setup' | 'analytics' | 'coordination'
      task_status: 'todo' | 'in_progress' | 'done'
      channel_type: 'social' | 'paid' | 'owned'
    }
  }
}
